---
- name: Add the encrypt variables
  include_vars: "vault.yml"
  
- name: MYSQL | config repo
  yum: name={{ item }} state=installed
  with_items:
    - "{{ mysql_repo_url }}"

- name: MYSQL | Install the mysql packages
  yum: name={{ item }} state=installed
  with_items:
    - "{{ mysql_pkgs }}"

- name: MYSQL | Copy the my.cnf file
  template: src=my.cnf.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify:
   - restart mysql

- name: MYSQL | Create the directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify:
   - restart mysql

- name: MYSQL |Start the mysql services
  service: name={{ mysql_service }} state=started enabled=yes

- name: MYSQL | update mysql root password 
  mysql_user: name=root password={{ mysql_root_db_pass }}


- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: MYSQL | Create the database
  mysql_db: name={{ item.name }} state=present
  with_items:
    - "{{ mysql_db }}"
  when: mysql_db|lower() != 'none'

- name: MYSQL | Create the database users
  mysql_user: name={{ item.name }}  password={{ item.pass|default("foobar") }}
                priv={{ item.priv|default("*.*:ALL") }} state=present host={{ item.host | default("localhost") }}
  with_items:
    - "{{ mysql_users }}"
  when: mysql_users|lower() != 'none'

